[package]
name = "listui"
version = "0.1.0"
edition = "2021"


[dependencies]
listui_lib = { path = "../listui_lib" }
tui = "0.19"
crossterm = "0.26.1"
dotenvy = "0.15"
once_cell = "1.17.1"
tokio = "1.26.0"
rand = "0.8.5"
dirs = "4.0.0"
argh = "0.1.10"
regex = "1"
lazy_static = "1.4.0"